In [ ]:
import pandas as pd
df = pd.read_csv("ramen-ratings.csv")
df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [ ]:
#To select the first row of data in a DataFrame
df.iloc[0]

Review #                         2580
Brand                       New Touch
Variety     T's Restaurant Tantanmen
Style                             Cup
Country                         Japan
Stars                            3.75
Top Ten                           NaN
Name: 0, dtype: object

In [5]:
#To get a column with iloc
df.iloc[:, 1]

0            New Touch
1             Just Way
2               Nissin
3              Wei Lih
4       Ching's Secret
             ...
2575             Vifon
2576           Wai Wai
2577           Wai Wai
2578           Wai Wai
2579          Westbrae
Name: Brand, Length: 2580, dtype: str

In [6]:
#To select just the second and third entries
df.iloc[1:3, 0]

1    2579
2    2578
Name: Review #, dtype: int64

In [13]:
#Label-based selection
df.loc[0, 'Country']

'Japan'

In [15]:
df.loc[:, ['Style', 'Country', 'Stars']]

     Style   Country Stars
0      Cup     Japan  3.75
1     Pack    Taiwan     1
2      Cup       USA  2.25
3     Pack    Taiwan  2.75
4     Pack     India  3.75
...    ...       ...   ...
2575  Bowl   Vietnam   3.5
2576  Pack  Thailand     1
2577  Pack  Thailand     2
2578  Pack  Thailand     2
2579  Pack       USA   0.5

[2580 rows x 3 columns]

In [ ]:
#Manipulating the Index
df.set_index('Style')

,Review #,Brand,Variety,Country,Stars,Top Ten
Style,,,,,,
Cup,2580,New Touch,T's Restaurant Tantanmen,Japan,3.75,NaN
Pack,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Taiwan,1,NaN
Cup,2578,Nissin,Cup Noodles Chicken Vegetable,USA,2.25,NaN
Pack,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Taiwan,2.75,NaN
Pack,2576,Ching's Secret,Singapore Curry,India,3.75,NaN
...,...,...,...,...,...,...
Bowl,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Vietnam,3.5,NaN
Pack,4,Wai Wai,Oriental Style Instant Noodles,Thailand,1,NaN
Pack,3,Wai Wai,Tom Yum Shrimp,Thailand,2,NaN
Pack,2,Wai Wai,Tom Yum Chili Flavor,Thailand,2,NaN
Pack,1,Westbrae,Miso Ramen,USA,0.5,NaN

In [23]:
df.describe()

          Review #
count  2580.000000
mean   1290.500000
std     744.926171
min       1.000000
25%     645.750000
50%    1290.500000
75%    1935.250000
max    2580.000000

In [ ]:
df.Country == 'Japan'

0        True
1       False
2       False
3       False
4       False
        ...
2575    False
2576    False
2577    False
2578    False
2579    False
Name: Country, Length: 2580, dtype: bool

In [26]:
df.loc[df.Country == 'Japan']

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
13,2567,Nissin,Deka Buto Kimchi Pork Flavor,Bowl,Japan,4.5,NaN
...,...,...,...,...,...,...,...
2554,26,Nissin,Soba Noodles With Mayo Mustard Squirt,Pack,Japan,4,NaN
2555,25,Nissin,Demae Ramen Spicy Flavor,Pack,Japan,3,NaN
2556,24,Nissin,Demae Ramen Spicy Seafood With Chili Pepper,Pack,Japan,2,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4
2568,12,Sapporo Ichiban,Shrimp Flavor,Pack,Japan,2.5,NaN

In [35]:
df.loc[df.Country.isin(['Japan', 'USA'])]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
...,...,...,...,...,...,...,...
2557,23,Nissin,Top Ramen Creamy Chicken,Pack,USA,4.5,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4
2568,12,Sapporo Ichiban,Shrimp Flavor,Pack,Japan,2.5,NaN
2570,10,Smack,Vegetable Beef,Pack,USA,1.5,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

In [38]:
df.loc[df.Stars.notnull()]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN