In [1]:
import pandas as pd

customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
payments = pd.read_csv("payments.csv")

In [2]:
customers.head()

  customer_id first_name last_name       city   country
0        C001      Ahmed    Rustam     Lahore  Pakistan
1        C002       Sara      Khan    Karachi  Pakistan
2        C003       John     Smith     London        UK
3        C004     Ayesha       Ali  Islamabad  Pakistan
4        C005      David       Lee    Toronto    Canada

In [3]:
products.head()

  product_id product_name     category  price
0       P001       Laptop  Electronics   1200
1       P002        Phone  Electronics    800
2       P003       Tablet  Electronics    600
3       P004   Headphones  Accessories    150
4       P005     Keyboard  Accessories    100

In [4]:
orders.head()

  order_id customer_id product_id  quantity  order_date
0     O001        C001       P001         1  2025-01-10
1     O002        C002       P002         2  2025-01-12
2     O003        C003       P004         3  2025-01-15
3     O004        C001       P005         2  2025-01-20
4     O005        C004       P003         1  2025-02-01

In [5]:
payments.head()

  payment_id order_id payment_method payment_status
0     PAY001     O001    Credit Card      Completed
1     PAY002     O002     Debit Card      Completed
2     PAY003     O003         PayPal      Completed
3     PAY004     O004           Cash        Pending
4     PAY005     O005    Credit Card      Completed

In [6]:
customerorder = pd.merge(customers, orders, left_on= 'customer_id', right_on= 'customer_id', how= 'outer')
customerorder

,customer_id,first_name,last_name,city,country,order_id,product_id,quantity,order_date
0,C001,Ahmed,Rustam,Lahore,Pakistan,O001,P001,1,2025-01-10
1,C001,Ahmed,Rustam,Lahore,Pakistan,O004,P005,2,2025-01-20
2,C002,Sara,Khan,Karachi,Pakistan,O002,P002,2,2025-01-12
3,C002,Sara,Khan,Karachi,Pakistan,O012,P001,1,2025-02-22
4,C003,John,Smith,London,UK,O003,P004,3,2025-01-15
5,C004,Ayesha,Ali,Islamabad,Pakistan,O005,P003,1,2025-02-01
6,C005,David,Lee,Toronto,Canada,O006,P007,1,2025-02-05
7,C006,Maria,Gomez,Madrid,Spain,O007,P009,5,2025-02-10
8,C007,Ali,Raza,Multan,Pakistan,O008,P006,2,2025-02-12
9,C008,Emma,Watson,Manchester,UK,O009,P008,1,2025-02-15
10,C009,Chen,Wei,Beijing,China,O010,P010,4,2025-02-18
11,C010,Lucas,Martin,Paris,France,O011,P002,1,2025-02-20

In [7]:
customerproducts = pd.merge(customerorder, products, left_on= 'product_id', right_on= 'product_id', how= 'outer')
customerproducts

,customer_id,first_name,last_name,city,country,order_id,product_id,quantity,order_date,product_name,category,price
0,C001,Ahmed,Rustam,Lahore,Pakistan,O001,P001,1,2025-01-10,Laptop,Electronics,1200
1,C002,Sara,Khan,Karachi,Pakistan,O012,P001,1,2025-02-22,Laptop,Electronics,1200
2,C002,Sara,Khan,Karachi,Pakistan,O002,P002,2,2025-01-12,Phone,Electronics,800
3,C010,Lucas,Martin,Paris,France,O011,P002,1,2025-02-20,Phone,Electronics,800
4,C004,Ayesha,Ali,Islamabad,Pakistan,O005,P003,1,2025-02-01,Tablet,Electronics,600
5,C003,John,Smith,London,UK,O003,P004,3,2025-01-15,Headphones,Accessories,150
6,C001,Ahmed,Rustam,Lahore,Pakistan,O004,P005,2,2025-01-20,Keyboard,Accessories,100
7,C007,Ali,Raza,Multan,Pakistan,O008,P006,2,2025-02-12,Chair,Furniture,250
8,C005,David,Lee,Toronto,Canada,O006,P007,1,2025-02-05,Desk,Furniture,400
9,C008,Emma,Watson,Manchester,UK,O009,P008,1,2025-02-15,Monitor,Electronics,300
10,C006,Maria,Gomez,Madrid,Spain,O007,P009,5,2025-02-10,Mouse,Accessories,50
11,C009,Chen,Wei,Beijing,China,O010,P010,4,2025-02-18,Printer,Electronics,200

In [8]:
orderdetails = pd.merge(customerproducts, payments, left_on= 'order_id', right_on= 'order_id', how= 'outer')
orderdetails

,customer_id,first_name,last_name,city,country,order_id,product_id,quantity,order_date,product_name,category,price,payment_id,payment_method,payment_status
0,C001,Ahmed,Rustam,Lahore,Pakistan,O001,P001,1,2025-01-10,Laptop,Electronics,1200,PAY001,Credit Card,Completed
1,C002,Sara,Khan,Karachi,Pakistan,O002,P002,2,2025-01-12,Phone,Electronics,800,PAY002,Debit Card,Completed
2,C003,John,Smith,London,UK,O003,P004,3,2025-01-15,Headphones,Accessories,150,PAY003,PayPal,Completed
3,C001,Ahmed,Rustam,Lahore,Pakistan,O004,P005,2,2025-01-20,Keyboard,Accessories,100,PAY004,Cash,Pending
4,C004,Ayesha,Ali,Islamabad,Pakistan,O005,P003,1,2025-02-01,Tablet,Electronics,600,PAY005,Credit Card,Completed
5,C005,David,Lee,Toronto,Canada,O006,P007,1,2025-02-05,Desk,Furniture,400,PAY006,Debit Card,Completed
6,C006,Maria,Gomez,Madrid,Spain,O007,P009,5,2025-02-10,Mouse,Accessories,50,PAY007,Cash,Completed
7,C007,Ali,Raza,Multan,Pakistan,O008,P006,2,2025-02-12,Chair,Furniture,250,PAY008,PayPal,Failed
8,C008,Emma,Watson,Manchester,UK,O009,P008,1,2025-02-15,Monitor,Electronics,300,PAY009,Credit Card,Completed
9,C009,Chen,Wei,Beijing,China,O010,P010,4,2025-02-18,Printer,Electronics,200,PAY010,Credit Card,Completed
10,C010,Lucas,Martin,Paris,France,O011,P002,1,2025-02-20,Phone,Electronics,800,PAY011,Debit Card,Completed
11,C002,Sara,Khan,Karachi,Pakistan,O012,P001,1,2025-02-22,Laptop,Electronics,1200,PAY012,Cash,Completed

In [9]:
# orderdetails.drop(columns='category')

In [10]:
orderdetails.insert(1, 'Full Name', 'N/A') 
orderdetails['Full Name'] = orderdetails['first_name'] + ' ' + orderdetails['last_name']
orderdetails.drop(columns = ['first_name', 'last_name'], inplace=True)
orderdetails.drop(columns= 'category', inplace=True)
orderdetails.drop(columns= ['payment_id', 'product_id', 'order_id', 'customer_id'], inplace=True)
orderdetails

,Full Name,city,country,quantity,order_date,product_name,price,payment_method,payment_status
0,Ahmed Rustam,Lahore,Pakistan,1,2025-01-10,Laptop,1200,Credit Card,Completed
1,Sara Khan,Karachi,Pakistan,2,2025-01-12,Phone,800,Debit Card,Completed
2,John Smith,London,UK,3,2025-01-15,Headphones,150,PayPal,Completed
3,Ahmed Rustam,Lahore,Pakistan,2,2025-01-20,Keyboard,100,Cash,Pending
4,Ayesha Ali,Islamabad,Pakistan,1,2025-02-01,Tablet,600,Credit Card,Completed
5,David Lee,Toronto,Canada,1,2025-02-05,Desk,400,Debit Card,Completed
6,Maria Gomez,Madrid,Spain,5,2025-02-10,Mouse,50,Cash,Completed
7,Ali Raza,Multan,Pakistan,2,2025-02-12,Chair,250,PayPal,Failed
8,Emma Watson,Manchester,UK,1,2025-02-15,Monitor,300,Credit Card,Completed
9,Chen Wei,Beijing,China,4,2025-02-18,Printer,200,Credit Card,Completed
10,Lucas Martin,Paris,France,1,2025-02-20,Phone,800,Debit Card,Completed
11,Sara Khan,Karachi,Pakistan,1,2025-02-22,Laptop,1200,Cash,Completed

In [11]:
orderdetails['Amount'] = orderdetails['quantity'] * orderdetails['price']
orderdetails

,Full Name,city,country,quantity,order_date,product_name,price,payment_method,payment_status,Amount
0,Ahmed Rustam,Lahore,Pakistan,1,2025-01-10,Laptop,1200,Credit Card,Completed,1200
1,Sara Khan,Karachi,Pakistan,2,2025-01-12,Phone,800,Debit Card,Completed,1600
2,John Smith,London,UK,3,2025-01-15,Headphones,150,PayPal,Completed,450
3,Ahmed Rustam,Lahore,Pakistan,2,2025-01-20,Keyboard,100,Cash,Pending,200
4,Ayesha Ali,Islamabad,Pakistan,1,2025-02-01,Tablet,600,Credit Card,Completed,600
5,David Lee,Toronto,Canada,1,2025-02-05,Desk,400,Debit Card,Completed,400
6,Maria Gomez,Madrid,Spain,5,2025-02-10,Mouse,50,Cash,Completed,250
7,Ali Raza,Multan,Pakistan,2,2025-02-12,Chair,250,PayPal,Failed,500
8,Emma Watson,Manchester,UK,1,2025-02-15,Monitor,300,Credit Card,Completed,300
9,Chen Wei,Beijing,China,4,2025-02-18,Printer,200,Credit Card,Completed,800
10,Lucas Martin,Paris,France,1,2025-02-20,Phone,800,Debit Card,Completed,800
11,Sara Khan,Karachi,Pakistan,1,2025-02-22,Laptop,1200,Cash,Completed,1200

In [12]:
orderdetails.groupby(['payment_status']).agg({'quantity': 'sum', 'price': 'sum'})

                quantity  price
payment_status
Completed             20   5700
Failed                 2    250
Pending                2    100

In [13]:
# orderdetails.loc[len(orderdetails)] = ["Louis", 'New York', 'USA', 10, '2026-03-03', 'Laptop', 1200, 'Cash', 'Completed', 12000]
orderdetails.to_csv("orderdetails.csv", index=False)