In [1]:
import pandas as pd
import numpy as np

bios = pd.read_csv("bios.csv")
coffee = pd.read_csv("coffee.csv")
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 11.1 MB

In [ ]:
bios.describe()

          athlete_id      height_cm      weight_kg
count  145500.000000  106651.000000  102070.000000
mean    73686.188955     176.333724      71.890996
std     42868.960158      10.380282      14.465540
min         1.000000     127.000000      25.000000
25%     36663.750000     170.000000      62.000000
50%     73302.500000     176.000000      70.000000
75%    110306.250000     183.000000      80.000000
max    149814.000000     226.000000     198.000000

In [ ]:
bios.loc[:5, 'NOC']

0    France
1    France
2    France
3    France
4    France
5    France
Name: NOC, dtype: str

In [ ]:
bios.iloc[0, 6]

'France'

In [20]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [46]:
# coffee.insert(3, 'Selling Price', 5.99)
# coffee.insert(4, 'Revenue', 1)
# coffee.insert(3, 'Production Cost', 0.99)
# coffee.insert(6, 'Profit', 0)

coffee['Selling Price'] = np.where(coffee['Coffee Type']  == 'Espresso', 3.99, 5.99)
coffee["Revenue"] = coffee["Units Sold"] * coffee["Selling Price"]
coffee["Production Cost"] = np.where(coffee['Coffee Type'] == 'Espresso', 0.99, 1.99)
coffee["Profit"] = coffee["Revenue"] - (coffee["Units Sold"] * coffee["Production Cost"])
coffee

,Day,Coffee Type,Units Sold,Production Cost,Selling Price,Revenue,Profit
0,Monday,Espresso,25,0.99,3.99,99.75,75.0
1,Monday,Latte,15,1.99,5.99,89.85,60.0
2,Tuesday,Espresso,30,0.99,3.99,119.70,90.0
3,Tuesday,Latte,20,1.99,5.99,119.80,80.0
4,Wednesday,Espresso,35,0.99,3.99,139.65,105.0
5,Wednesday,Latte,25,1.99,5.99,149.75,100.0
6,Thursday,Espresso,40,0.99,3.99,159.60,120.0
7,Thursday,Latte,30,1.99,5.99,179.70,120.0
8,Friday,Espresso,45,0.99,3.99,179.55,135.0
9,Friday,Latte,35,1.99,5.99,209.65,140.0
10,Saturday,Espresso,45,0.99,3.99,179.55,135.0
11,Saturday,Latte,35,1.99,5.99,209.65,140.0
12,Sunday,Espresso,45,0.99,3.99,179.55,135.0
13,Sunday,Latte,35,1.99,5.99,209.65,140.0

In [ ]:
# bios.sample(5)
# bios.loc[bios['born_country'] == 'KSA']
# bios[(bios['name'].str.contains("Ahmed|Saad", case=False)) & (bios['born_country'].isin(['USA', 'KSA', 'QTR']))]
# bios.drop(columns = ['born_city'], inplace=True)
# bios.drop(columns = ['born_region'], inplace=True)
bios.head()

,athlete_id,name,born_date,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,GBR,France,NaN,NaN,1930-07-25

In [90]:
bios['born_datetime'] = pd.to_datetime(bios['born_date'])
bios['born_year'] = bios['born_datetime'].dt.year
# bios[['name', 'born_year']]
bios.head()

,athlete_id,name,born_date,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0

In [92]:
bios['weight'] = bios['weight_kg'].apply(lambda x: 'Light' if x < 60 else ('Heavy' if x > 75 else 'Normal'))
bios.head(25)

,athlete_id,name,born_date,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,weight
0,1,Jean-François Blanchy,1886-12-12,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,Normal
1,2,Arnaud Boetsch,1969-04-01,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,Heavy
2,3,Jean Borotra,1898-08-13,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,Heavy
3,4,Jacques Brugnon,1895-05-11,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,Normal
4,5,Albert Canet,1878-04-17,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,Normal
5,6,Nicolas Chatelain,1970-01-13,FRA,France,181.0,70.0,NaN,1970-01-13,1970.0,Normal
6,7,Patrick Chila,1969-11-27,FRA,France,180.0,73.0,NaN,1969-11-27,1969.0,Normal
7,8,Henri Cochet,1901-12-14,FRA,France,NaN,NaN,1987-04-02,1901-12-14,1901.0,Normal
8,9,Marcel Cousin,1896-08-04,FRA,France,NaN,NaN,1986-08-01,1896-08-04,1896.0,Normal
9,10,Guy de la Chapelle,1868-07-16,FRA,France,NaN,NaN,1923-08-27,1868-07-16,1868.0,Normal
10,11,"Élie, Comte de Lastours",1874-08-12,FRA,France,NaN,NaN,1932-11-18,1874-08-12,1874.0,Normal
11,12,Max Decugis,1882-09-24,FRA,France,NaN,NaN,1978-09-06,1882-09-24,1882.0,Normal
12,13,J. Defert,NaN,NaN,France,NaN,NaN,NaN,NaT,NaN,Normal
13,14,Étienne Durand,NaN,NaN,France,NaN,NaN,NaN,NaT,NaN,Normal
14,15,Damien Éloi,1969-07-04,FRA,France,165.0,58.0,NaN,1969-07-04,1969.0,Light
15,16,Adrien Fauchier-Magnan,1873-11-19,FRA,France,NaN,NaN,1965-08-06,1873-11-19,1873.0,Normal
16,17,Guy Forget,1965-01-04,MAR,France,189.0,79.0,NaN,1965-01-04,1965.0,Heavy
17,18,Jean-Philippe Gatien,1968-10-16,FRA,France,178.0,73.0,NaN,1968-10-16,1968.0,Normal
18,19,Maurice Germot,1882-11-15,FRA,France,NaN,NaN,1958-08-06,1882-11-15,1882.0,Normal
19,20,André Gobert,1890-09-30,FRA,France,NaN,NaN,1951-12-06,1890-09-30,1890.0,Normal
20,21,Pierre Hirsch,1900-11-08,FRA,France,NaN,NaN,1942-04-19,1900-11-08,1900.0,Normal
21,22,René Lacoste,1904-07-02,FRA,France,NaN,NaN,1996-10-12,1904-07-02,1904.0,Normal
22,23,Daniel Lawton,1881-11-27,FRA,France,NaN,NaN,1979-03-27,1881-11-27,1881.0,Normal
23,24,Paul Lebreton,1875-10-19,FRA,France,NaN,NaN,1960-03-31,1875-10-19,1875.0,Normal
24,25,Paul Lecaron,1863-07-29,FRA,France,NaN,NaN,1940-09-17,1863-07-29,1863.0,Normal

In [94]:
ahmed = bios[bios['name'].str.contains("Ahmed", case=False)]
saad = bios[bios['name'].str.contains("Saad", case=False)]
ahmed_saad = pd.concat([ahmed, saad])
ahmed_saad

,athlete_id,name,born_date,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,weight
1806,1813,Ahmed El-Said,1970-04-15,EGY,Egypt,NaN,NaN,NaN,1970-04-15,1970.0,Normal
1807,1814,Mahmoud Ahmed,1945-09-12,EGY,Egypt,182.0,81.0,NaN,1945-09-12,1945.0,Heavy
1817,1825,Ahmed El-Gindy,1959-01-21,NaN,Egypt,178.0,75.0,NaN,1959-01-21,1959.0,Normal
1821,1829,Ahmed El-Minabawi,1928-07-21,EGY,Egypt,NaN,NaN,NaN,1928-07-21,1928.0,Normal
1823,1831,Ahmed El-Nagar,1964-02-19,NaN,Egypt,180.0,81.0,NaN,1964-02-19,1964.0,Heavy
...,...,...,...,...,...,...,...,...,...,...,...
133111,136036,Man Asaad,1993-11-20,SYR,Syrian Arab Republic,190.0,143.0,NaN,1993-11-20,1993.0,Heavy
133168,136096,Atef Saad,1988-03-20,TUN,Tunisia,176.0,57.0,NaN,1988-03-20,1988.0,Light
133188,136119,Mohamed Saadaoui,1995-05-11,TUN,Tunisia,176.0,86.0,NaN,1995-05-11,1995.0,Heavy
133225,136162,Yaaqoub Al-Saadi,1996-06-13,NaN,United Arab Emirates,175.0,62.0,NaN,1996-06-13,1996.0,Normal
142496,146108,Saadat Dalgatova,1988-10-30,NaN,ROC,NaN,NaN,NaN,1988-10-30,1988.0,Normal

In [98]:
noc = pd.read_csv("noc_regions.csv")
bios_n = pd.merge(bios, noc, left_on='born_country', right_on='NOC', how='inner', suffixes=["bios", "noc"])
bios_n

,athlete_id,name,born_date,born_country,NOCbios,height_cm,weight_kg,died_date,born_datetime,born_year,weight,NOCnoc,region,notes
0,1,Jean-François Blanchy,1886-12-12,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,Normal,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,Heavy,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,Heavy,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,Normal,FRA,France,NaN
4,5,Albert Canet,1878-04-17,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,Normal,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110634,149222,Polina Luchnikova,2002-01-30,RUS,ROC,167.0,61.0,NaN,2002-01-30,2002.0,Normal,RUS,Russia,NaN
110635,149223,Valeriya Merkusheva,1999-09-20,RUS,ROC,168.0,65.0,NaN,1999-09-20,1999.0,Normal,RUS,Russia,NaN
110636,149224,Yuliya Smirnova,1998-05-08,RUS,ROC,163.0,55.0,NaN,1998-05-08,1998.0,Light,RUS,Russia,NaN
110637,149225,André Foussard,1899-05-19,FRA,France,166.0,NaN,1986-03-18,1899-05-19,1899.0,Normal,FRA,France,NaN
110638,149814,Bill Phillips,1913-07-15,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,1913.0,Normal,AUS,Australia,NaN

In [ ]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_country   110908 non-null  str
 4   NOC            145499 non-null  str
 5   height_cm      106651 non-null  float64
 6   weight_kg      102070 non-null  float64
 7   died_date      33940 non-null   str
 8   born_datetime  143693 non-null  datetime64[us]
 9   born_year      143693 non-null  float64
 10  weight         145500 non-null  str
dtypes: datetime64[us](1), float64(3), int64(1), str(6)
memory usage: 12.2 MB

In [103]:
bios.isna().sum()

athlete_id            0
name                  0
born_date          1807
born_country      34592
NOC                   1
height_cm         38849
weight_kg         43430
died_date        111560
born_datetime      1807
born_year          1807
weight                0
dtype: int64

In [4]:
coffee.groupby(['Day'])['Units Sold'].sum()

Day
Friday       80
Monday       40
Saturday     80
Sunday       80
Thursday     70
Tuesday      50
Wednesday    60
Name: Units Sold, dtype: int64

In [28]:
# bios['born_city'].value_counts(sort=False)
# bios.info()
# bios['height_cm'].dropna(inplace=True)
bios.groupby('weight_kg').mean()
# bios['weight_kg'].isna()
# bios['weight_kg'].dropna(inplace=True)

TypeError: dtype 'str' does not support operation 'mean'

In [44]:
coffee['Units Sold'].mean()
coffee.head()
coffee[['Coffee Type', 'Units Sold']].plot.line()
# coffee.groupby('Units Sold').mean(numeric_only=True)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.